apiVersion: v1
kind: Template
metadata:
  name: msb
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: msb
      labels:
        app:  managed-services-broker
        service: msb
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: msb-tls
    spec:
      selector:
        app:  managed-services-broker
        service: msb
      ports:
      - protocol: TCP
        port: 80
        targetPort: 8080

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: msb
      labels:
        app:  managed-services-broker
        service: msb
    spec:
      replicas: 1
      selector:
        matchLabels:
          app:  managed-services-broker
      template:
        metadata:
          labels:
            app:  managed-services-broker
            service: msb
        spec:
          containers:
          - name: managed-services-broker
            image: ${IMAGE_ORG}/${IMAGE_NAME}:${IMAGE_TAG}
            imagePullPolicy: ${IMAGE_PULL_POLICY}
            args:
            - --port
            - "8080"
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ROUTE_SUFFIX
              value: ${ROUTE_SUFFIX}
            - name: LAUNCHER_DASHBOARD_URL
              value: ${LAUNCHER_DASHBOARD_URL}
            - name: CHE_DASHBOARD_URL
              value: ${CHE_DASHBOARD_URL}
            ports:
            - containerPort: 8080
            readinessProbe:
              tcpSocket:
                port: 8080
              failureThreshold: 1
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
            livenessProbe:
              tcpSocket:
                port: 8080
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2

  - apiVersion: v1
    kind: Route
    metadata:
      name: msb
      labels:
        app: managed-services-broker
        service: msb
    spec:
      to:
        kind: Service
        name: msb
      port:
        targetPort: 8080

  - apiVersion: servicecatalog.k8s.io/v1beta1
    kind: ClusterServiceBroker
    metadata:
      name: managed-services-broker
    spec:
      url: http://msb-${NAMESPACE}.${ROUTE_SUFFIX}

parameters:
  - name: NAMESPACE
    description: Namespace of the project that is being deployed to
    value: "managed-services-broker"

  - name: IMAGE_ORG
    description: Name of the broker image org
    value: aerogear

  - name: IMAGE_NAME
    description: Name of the broker image
    value: "managed-services-broker"

  - name: IMAGE_TAG
    description: Tag of the broker image
    value: "1.0.0"

  - name: IMAGE_PULL_POLICY
    value: "Always"

  - name: ROUTE_SUFFIX
    description: Cluster route subdomain
    required: true

  - name: LAUNCHER_DASHBOARD_URL
    description: Launcher dasbhoard url
    required: true
  
  - name: CHE_DASHBOARD_URL
    description: Che dasbhoard url
    required: true

  - name: CA_BUNDLE
    value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTFNVFUwTWpnM01qQXdIaGNOTVRnd01UQTRNVFl5TlRJd1doY05Nak13TVRBMwpNVFl5TlRJeFdqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUxTVRVME1qZzNNakF3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNjNmRIWGdHQ3Q0UjFEMFBBOTlTYmUKUkI3TW1KdWIyaEtrMUFGVTBQdTkzUlNZT3k5OUtLZmRCazhWMENnMWx4UjhlRHI5OHJXOWg1MmptZ1Z2cU5aZwpka203R05ONXFpaUdscnRZcDN5QmM4dUMwSEpuV2kzOFVqK1loaXMvUVNYSVlDMWxmemlmZC9mWFZndmZHMFRvCk9zTFUzWHViWk5sRFgzVVJSblVoeTl2ZktBbkt2bXM5akdRaXFrSHNWZVpVaEl6alpuQ0k4MFZDM2lCOFRkK3kKeWUvcmxWVWVtUWFDSWxqT0RlK3lzK2pyRXlnTk5wc0lVdHJHODRYTkJjVmdSQWF6a3BCNEdxL1A4U3NWc0xwYwppcUFRcWxpcWpUVFlMVFVjYk5wYUxEVWgxWWtXS1VIaHR5WWhLcEtHcFZ6RExnMUZNZE9YemwvOTVIV1dDNElECkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQTVKdmNGMjlyK3ptbkdxOGI3MXprTGlEbjJKUTQ1OWI1NVJ3cnVDZzJvcVprTAovRWV1RldQM2dwN0FvZjRNNXRPSTNRb0lrcVJWYzBQaXJqekFlVnQzeHlDNENsR0pkelZ1c3ljc3h0SVFyaVVoCjcwUElSUHVUZ0VyNjc2QXhrLzAyMVEremFuR0ZpakVBNjR1eG5abDVkb3I2WFRGcjdaTEd1a25QUm9QRVlLaFMKazNGQ3RLYWN1SXZlL2JDajlVdGVnM3dHK0NkUEhLV08yMlNUd1VjeFIxb3daNS9JZ1BndHV3SkF6SWVVdUlCcwpIRk5WemhaWXVZYXlNYWp1dFdsdGtFMVJCTVA3ajlUQythS240MUg1MmpRTlNoU1lQajlmbFhzSmxGZXVqT3dyCkYyWU43WnVrbmtKOGRZcTE3QjdqNm5SR3YzUTVzajdhZ3BWVnRWeUMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5URTFOREk0TnpJeE1CNFhEVEU0TURFdwpPREUyTWpVeU1Gb1hEVEl6TURFd056RTJNalV5TVZvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFV4TlRReU9EY3lNVENDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBSjR1MEJZa3BpVklVRXowK09tclJKcVA2Z3BXN2psc3BVN2pEb0NtVmJodwpsaG9mKzBaclg2SVcyWHlUNjRlWHVrUEI5anB3bGlSZVlPR1Y3bmVCbTZZTHFFZmx5cDE2Vm9OTXVxUFg5a1VmClFkRGtlU1Q1aEpZdW02WjNhanQ2VlQ3YTdGcWRtczZ5UWxQMC95ZS9lN2xDNVZZMDNpUWNwUnZlRUQ0SVZoV2QKcmFucHIrNlREcVpZRTVFRUhISE53cS9YTGNxSTRQSUh6OU5kc2R1ZmY4UDJnNjk5VllpSkZTN0xpVlBaNkpGdAp0djliY3l1czNUQmUxYSt0U3QydWFZRlNZdG1nQ2hBUkFKZ0FtUFYyLy9rSGJwaDUrVlNHSlUwUExjT0dLZkFnCkdSSko1bXMyMUE3ZnhzeVVoMkVuV2R4c1hvWWEzWlhUNmlGZllDM0RCdjBDQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhJOApROEZaYmRpNG10VkhPYmp5ZWZBTm1kVjZTWVZrRGU2UXM4RE1jd3U5VG5VRGZ2d1kyRWxHSGpSYUdOd3BhcDRzCkVhR1h6RG5vTnh1VTE4eTYrRnJ2KzBLTHp5dHNaRXJRTVRibkZHZDZkV0ZUR0hMRGx4VEk2RUJBaVBzd0luRUsKT0VkT3JNQXduMGZNcjRlNWYyYXVhOUNaNW5Fb0ZOWVhaMVdUbE5kSjNtYjE1MzQ2OXBpZ21jTmNET2Ztd0dLcApFNU96T3paU25SNnpXZG5ydVRsTGxneVNBc2FZUkNSalFmMkhHUmwzUEhBTzMzalB2MDFIcDFsQUd2ODB0NmFpCkpjWC8xZWVBZkQ2TSsvVzRlcjlsU1QvdktNR3N0UFdvUUNsT0lsanZzOVFJemw3bjVjVnd1OW5XVzNlRVNpVXoKbnFRZ1krVGlwTk5TeWFFV0N0TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
